name: Compile and Deploy Resume PDF

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: latest

      - name: Compile Resume PDF
        run: |
          mkdir -p public
          typst compile resume.typ public/CV.pdf

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
